# build environment
FROM node:16-alpine as builder
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

ARG REACT_APP_ISEE_API
ENV REACT_APP_ISEE_API=$REACT_APP_ISEE_API

ARG REACT_APP_ISEE_ONTOAPI
ENV REACT_APP_ISEE_ONTOAPI=$REACT_APP_ISEE_ONTOAPI

COPY package.json ./
RUN npm i
COPY . ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]