const DATA_FILEDS = {
    AITask: [
        "Abductive Task",
        "Rule Based",
        "Deductive Task",
        "Inductive Task",
        "Forecasting",
        "Anomaly Detection",
        "Audio Processing",
        "Autonomous Driving",
        "Classification",
        "Binary Classification",
        "Multi-class Classification",
        "Multi-label Classification",
        "Clustering",
        "Divisive Clustering",
        "Hierarchical Clustering",
        "Computational Linguistics",
        "Automatic Speech Recognition",
        "Machine Translation",
        "Text Summarisation",
        "Computer Vision",
        "Edge Detection",
        "Face Recognition",
        "Image Detection",
        "Image Generation",
        "Image Restoration",
        "Image Segmentation",
        "Object Tracking",
        "Video Motion Tracking",
        "Forcasting",
        "Information Retrieval",
        "Ranking",
        "Recommendation",
        "Optimisation",
        "Regression",
        "Signal Processing"
    ],
    DatasetType: ["multivariate",
        "univariate",
        "image",
        "text",
        "time-series"],
    AIMethod: [
        "Computer Heuristics",
        "Metaheuristics",
        "Convolutional Neural Network",
        "Dimensionality Reduction",
        "Discrete Cosine Transformation",
        "Flexible Discriminant Analysis",
        "Fourier Transformation",
        "Linear Discriminant Analysis",
        "Mixture Discriminant Analysis",
        "Partial Least Squares Regression",
        "Principal Component Analysis",
        "Quadratic Discriminant Analysis",
        "Sammon Mapping",
        "t-SNE",
        "Fuzzy Logic",
        "Instance Based Learning",
        "Case Based Reasoning",
        "k-Nearest Neighbour",
        "Knowledge based Systems",
        "Expert Systems",
        "Knowledge Bases",
        "Biological Ontologies",
        "Machine Learning",
        "Reinforcement Learning",
        "Policy-based Reinforcement Learning",
        "Q-Learning",
        "SARSA",
        "Temporal Difference",
        "Supervised Machine Learning",
        "Decision Tree",
        "Deep Belief Network",
        "Ensemble Method",
        "AdaBoost",
        "Bootstrapped Aggregation",
        "Gradient Boosting",
        "Gradient Tree Boosting"
    ],
    Datatype: [
        "categorical",
        "numerical",
        "ordinal"],
    ModelOutcome: ['Binary', 'Multi-Class', 'Range'],
    AssetmentType: ['Accuracy', 'F1 Score', "Precision", "Recall", "AUC", "Error Rate", "Top K Accuracy", "Jaccard Score", "Explained Variance", "Mean Absolute Error", "Mean Squared Error", "Adjusted Mutual Info Score", "Adjusted Rand Score", "Completeness Score", "Mutual Info Score"],
    IntentType: [
        'Debugging',
        'Education',
        'Effectiveness',
        'Efficiency',
        'Persuasiveness',
        'Satisfaction',
        'Scruitablity',
        'Transparency',
        'Trust',
    ],
    QUESTION_CATEGORY: [
        'Goodness',
        'Satisfaction',
        'Mental Model',
        'Curiosity',
        'Trust',
        'Performance',
        'Custom'
    ],
    QUESTION_METRIC: ['Free-Text', 'Number', 'Radio', 'Checkbox', 'Likert'],
};


export default DATA_FILEDS;