const TOOL_TIPS = {
    ai_settings_info: "Step 1: Describe the AI model.",
    name: "Please enter a unique name for your use case.",
    goal: "Please describe what you want to achieve by using the iSee system. For example: 'To explain the outcomes of the AI system to staff and customers'",
    domain: "Please select the most appropriate sector for your AI system.",
    ai_task: "Please describe the goal of your AI system. For example: 'An AI system to diagnose fractures in x-ray images.'",
    ai_method: "Please select the techniques used to build the AI system.",
    data_info: "Step 2: Now tell us a little about your data.",
    dataset_type: "Please select the appropriate dataset type for the AI system. A description of each type is provided.",
    data_type: "Please select all appropriate datatypes from the below list. Your dataset may have one or multiple types.",
    num_features: "Please select how many features/attributes are present in the tabular dataset.",
    num_instances: "Please select the number of examples/instances used to train the AI system.",
    assesment_info_box_old: "Please describe how the performance for the AI system was measured. Common metrics are available in the dropdown.",
    assesment_info: "Step 3: Next, describe any relevant performance measures for the AI model.",
    assesment_type: "Please enter the name of the metric.",
    assesment_val: "Please enter the value of the metric.",
    model_info: "Step 4: Please provide a means to access your AI model. ",
    model_mode: "Please select how you would like to share details of the AI model with iSee.",
    model_mode_file: "If you are able to share the AI model with iSee, please upload a copy of your model below.",
    model_mode_api: "If you are unable to share the AI model, please share an API endpoint by which iSee can access your model predictions.",
    model_backend: "Please identify which framework you have used to develop your AI model. The iSee platform is compatible with all frameworks in the below dropdown list.",
    model_file: "Please upload the model using any of the supported file formats (json, h5, csv and pkl)",
    model_dataset: "Please provide a sample of functional input data for your AI model. These will be used to parameterise data-dependant explanations where appropriate. - For tabular, text or timeseries datasets, please provide a .CSV file. - For image datasets, please provide a ZIP folder of your images.",
    model_config: "Please provide the configuration files for your AI model.",
    persona_create_info: "Please enter the details of the stakeholder groups you wish to benefit from the explanation of your AI system. We describe each group in the iSee system as a 'Persona'",
    persona_info: "Step 5: Almost there! Now tell us a little about the users of the AI system.",
    persona_name: "Please enter a name for the persona.",
    persona_domain_knowledge_level: "Please enter the domain/sector knowledge that a representative of this stakeholder group is likely to have. For example: in the medical domain, patients are likely to have low domain knowledge, while clinicians are likely to have high domain knowledge.",
    persona_ai_knowledge_level: "Please enter the knowledge of AI that a representative of this stakeholder group is likely to have. For example: users of the system may have low general knowledge of AI, while system auditors are likely to have high knowledge of AI.",
    persona_intent_btn: "Please click this button to add an Intent Question for your persona. Intent Questions describe one explanation goal. Each Persona must have at least one Intent Question, and may have multiple. For example: The user of a movie recommender may ask 'why is this movie relevant to me?'.",
    persona_intent_info: "Step 7: Try to express what each persona wants to understand about the system.",
    persona_intent_create: "Please select an Intent Question from the list. Try to select the question which most closely represents the personas needs. After selection, you can personalise the text.",
    persona_strategy_info: "Step 8: Once all previous steps have been completed, please click the 'Retrieve Explanation Strategy'.",
    persona_eval_info: "Step 9: Finally, give us a few details about how each persona will judge the quality of the provided explanation. "
}

export default TOOL_TIPS;
